### PR TITLE
Bump Version + Add support for arm64/armhf

### PR DESCRIPTION
**Pull request by navanchauhan**
## Problem

- v2.1.0
- Only amd64 support

## Solution

- Bump version for prebuilt amd64 binary 
- Build from source for arm64 and armhf

## PR Status

- [x ] Code finished and ready to be reviewed/tested
- [x ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
Also @ericgaspar I saw that there is no maintainer listed in the `manifest.json` file. I am happy to take it over and maintain it

**Comment by ericgaspar** [comment]
Cool! Go for it.

**Comment by navanchauhan** [comment]
Awesome. Let me know once you give me write access

**Pull request merged**
